# Generated by Django 4.2.26 on 2026-06-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0002_quoterequest_alter_contactmessage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="artwork",
            field=models.FileField(blank=True, null=True, upload_to="quotes/artwork/"),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="colors",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="decoration",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="quotes/logos/"),
        ),
    ]
