# Generated by Django 4.2.26 on 2026-06-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0003_quoterequest_artwork_quoterequest_colors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("reviewing", "Reviewing"),
                    ("quoted", "Quoted"),
                    ("ordered", "Ordered"),
                    ("shipped", "Shipped"),
                ],
                default="new",
                max_length=30,
            ),
        ),
    ]
