# Generated by Django 4.2.26 on 2026-07-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0004_quoterequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="estimated_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="in_production",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="is_returning_customer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="lead_source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                    ("linkedin", "LinkedIn"),
                    ("referral", "Referral"),
                    ("repeat", "Returning Customer"),
                    ("other", "Other"),
                ],
                default="website",
                max_length=40,
            ),
        ),
    ]
