# Generated by Django 4.2.26 on 2026-07-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_quote_quoteitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="quotes/pdfs/"),
        ),
    ]
