# Generated by Django 4.2.26 on 2026-07-09 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0005_quote_pdf_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("product_slug", models.SlugField(blank=True)),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("product_detail", "Product Detail"),
                            ("customer_dashboard", "Customer Dashboard"),
                            ("quote_builder", "Quote Builder"),
                        ],
                        max_length=60,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
