# Generated by Django 4.2.26 on 2026-07-10 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0007_product_inventory_status_product_supplier_inventory_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="supplier_last_sync",
        ),
    ]
