# Generated by Django 4.2.26 on 2026-07-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_supplierpurchaseorder_supplierpurchaseorderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Supplier email address used for purchase orders.",
                max_length=254,
            ),
        ),
    ]
