# Generated by Django 4.2.26 on 2026-07-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_supplier_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierpurchaseorder",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="supplier_purchase_orders/"
            ),
        ),
    ]
