# Generated by Django 4.2.26 on 2026-07-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_supplierpurchaseorder_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierpurchaseorder",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierpurchaseorder",
            name="estimated_ship_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierpurchaseorder",
            name="production_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierpurchaseorder",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierpurchaseorder",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierpurchaseorder",
            name="tracking_url",
            field=models.URLField(blank=True),
        ),
    ]
