# Generated by Django 4.2.26 on 2026-07-14 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0012_supplierpurchaseorder_confirmed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierPurchaseOrderActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pdf_generated", "PDF Generated"),
                            ("sent", "Sent"),
                            ("status_changed", "Status Changed"),
                            ("tracking_updated", "Tracking Updated"),
                            (
                                "supplier_reference_updated",
                                "Supplier Reference Updated",
                            ),
                            ("notes_updated", "Notes Updated"),
                            ("sync", "Fulfillment Synchronized"),
                            ("error", "Error"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("previous_value", models.CharField(blank=True, max_length=255)),
                ("new_value", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_po_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="products.supplierpurchaseorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
