# Generated by Django 4.2.26 on 2026-07-19 15:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_supplierpurchaseorderactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_product_id",
                    models.CharField(
                        blank=True,
                        help_text="Supplier-side product identifier.",
                        max_length=160,
                    ),
                ),
                (
                    "supplier_sku",
                    models.CharField(
                        blank=True, help_text="Supplier-specific SKU.", max_length=160
                    ),
                ),
                (
                    "supplier_product_name",
                    models.CharField(
                        blank=True,
                        help_text="Product name as shown by the supplier.",
                        max_length=220,
                    ),
                ),
                ("supplier_url", models.URLField(blank=True)),
                ("external_image_url", models.URLField(blank=True)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "setup_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "minimum_order_quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("inventory_quantity", models.IntegerField(blank=True, null=True)),
                (
                    "inventory_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("in_stock", "In Stock"),
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "production_lead_time_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "decoration_methods",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated supplier decoration methods.",
                        max_length=500,
                    ),
                ),
                (
                    "available_colors",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated supplier color options.",
                        max_length=500,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("api", "Supplier API"),
                            ("csv", "CSV Import"),
                            ("catalog", "Supplier Catalog"),
                            ("sync", "Automated Sync"),
                            ("other", "Other"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                (
                    "source_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw normalized supplier data used to create this listing.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False,
                        help_text="Marks the preferred supplier offer for this product.",
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_listings",
                        to="products.suppliercatalog",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_listings",
                        to="products.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_listings",
                        to="products.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier listing",
                "verbose_name_plural": "Supplier listings",
                "ordering": ["product__name", "-is_preferred", "supplier__name"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_active"],
                        name="listing_product_active_idx",
                    ),
                    models.Index(
                        fields=["supplier", "is_active"],
                        name="listing_supplier_active_idx",
                    ),
                    models.Index(
                        fields=["inventory_status"], name="listing_inventory_idx"
                    ),
                    models.Index(fields=["source"], name="listing_source_idx"),
                    models.Index(
                        fields=["last_synced_at"], name="listing_last_sync_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="supplierlisting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("supplier_sku", ""), _negated=True),
                fields=("supplier", "supplier_sku"),
                name="uniq_supplier_listing_sku",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierlisting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("supplier_product_id", ""), _negated=True),
                fields=("supplier", "supplier_product_id"),
                name="uniq_supplier_listing_product_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierlisting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_preferred", True)),
                fields=("product",),
                name="uniq_preferred_listing_per_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierlisting",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("inventory_quantity__isnull", True),
                    ("inventory_quantity__gte", 0),
                    _connector="OR",
                ),
                name="supplier_listing_inventory_nonnegative",
            ),
        ),
    ]
