# Generated by Django 4.2.26 on 2026-07-19 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0019_alter_orderitem_options_orderitem_product_and_more"),
        ("products", "0014_supplierlisting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierpurchaseorderitem",
            name="minimum_quantity_snapshot",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierpurchaseorderitem",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_purchase_order_items",
                to="customers.orderitem",
            ),
        ),
        migrations.AddField(
            model_name="supplierpurchaseorderitem",
            name="setup_cost_snapshot",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="supplierpurchaseorderitem",
            name="supplier_catalog_snapshot",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="supplierpurchaseorderitem",
            name="supplier_listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_order_items",
                to="products.supplierlisting",
            ),
        ),
        migrations.AddField(
            model_name="supplierpurchaseorderitem",
            name="supplier_product_id_snapshot",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="supplierpurchaseorderitem",
            name="supplier_product_name_snapshot",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="supplierpurchaseorderitem",
            name="supplier_source_snapshot",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
