# Generated by Django 4.2.26 on 2026-07-20 12:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0015_supplierpurchaseorderitem_minimum_quantity_snapshot_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierIntegrationAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("operation", models.CharField(blank=True, max_length=100)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("url", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("success", models.BooleanField(db_index=True, default=False)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("request_metadata", models.JSONField(blank=True, default=dict)),
                ("response_metadata", models.JSONField(blank=True, default=dict)),
                ("error_type", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_audit_logs",
                        to="products.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["supplier", "operation", "status"],
                        name="supplier_audit_lookup_idx",
                    ),
                    models.Index(
                        fields=["correlation_id", "started_at"],
                        name="supplier_corr_time_idx",
                    ),
                ],
            },
        ),
    ]
