# Generated by Django 4.2.26 on 2026-07-20 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0016_supplierintegrationauditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierSyncBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("partial", "Partially completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_operations", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("total_jobs", models.PositiveIntegerField(default=0)),
                ("completed_jobs", models.PositiveIntegerField(default=0)),
                ("successful_jobs", models.PositiveIntegerField(default=0)),
                ("failed_jobs", models.PositiveIntegerField(default=0)),
                ("skipped_jobs", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_sync_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierSyncJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operation", models.CharField(db_index=True, max_length=100)),
                ("sequence", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("records_processed", models.PositiveIntegerField(default=0)),
                ("records_succeeded", models.PositiveIntegerField(default=0)),
                ("records_failed", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("result_metadata", models.JSONField(blank=True, default=dict)),
                ("error_type", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="products.suppliersyncbatch",
                    ),
                ),
                (
                    "depends_on",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_jobs",
                        to="products.suppliersyncjob",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_jobs",
                        to="products.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierSyncCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cursor", models.CharField(blank=True, max_length=500)),
                ("page", models.PositiveIntegerField(default=0)),
                ("offset", models.PositiveIntegerField(default=0)),
                ("last_external_id", models.CharField(blank=True, max_length=255)),
                ("state", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoint",
                        to="products.suppliersyncjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="suppliersyncjob",
            index=models.Index(
                fields=["batch", "status", "sequence"], name="supplier_job_batch_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suppliersyncjob",
            index=models.Index(
                fields=["supplier", "operation", "status"],
                name="supplier_job_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliersyncjob",
            constraint=models.UniqueConstraint(
                fields=("batch", "supplier", "operation"),
                name="unique_supplier_operation_per_batch",
            ),
        ),
        migrations.AddIndex(
            model_name="suppliersyncbatch",
            index=models.Index(
                fields=["status", "created_at"], name="supplier_batch_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suppliersyncbatch",
            index=models.Index(
                fields=["correlation_id"], name="supplier_batch_corr_idx"
            ),
        ),
    ]
