# Generated by Django 4.2.26 on 2026-07-21 23:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_suppliersyncbatch_suppliersyncjob_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageProductRail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                (
                    "rail_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Products"),
                            ("featured", "Featured Products"),
                            ("newest", "Newest Products"),
                            ("category", "Category"),
                            ("industry", "Industry"),
                            ("collection", "Collection"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("max_products", models.PositiveIntegerField(default=12)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ImprintMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "setup_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=80)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="marketplace/industries/"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Industries",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="marketplace/collections/"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("value", models.CharField(max_length=500)),
                ("unit", models.CharField(blank=True, max_length=60)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_highlighted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["product__name", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("sku", models.CharField(blank=True, max_length=120)),
                ("supplier_sku", models.CharField(blank=True, max_length=160)),
                ("color", models.CharField(blank=True, max_length=120)),
                ("size", models.CharField(blank=True, max_length=120)),
                ("material", models.CharField(blank=True, max_length=120)),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("inventory_quantity", models.IntegerField(blank=True, null=True)),
                (
                    "inventory_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("in_stock", "In Stock"),
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("source_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["product__name", "order", "name"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="products.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="suppliercatalog",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="supplier_catalogs/"
            ),
        ),
        migrations.AddField(
            model_name="suppliercatalog",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="Supplier-side catalog identifier.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="suppliercatalog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="suppliercatalog",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("csv", "CSV"),
                    ("api", "API"),
                    ("feed", "Supplier Feed"),
                    ("other", "Other"),
                ],
                default="manual",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="suppliercatalog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="suppliercatalog",
            name="valid_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suppliercatalog",
            name="valid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suppliercatalog",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent", "is_active", "order"],
                name="category_parent_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_featured", "created_at"],
                name="product_marketplace_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="product_category_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suppliercatalog",
            index=models.Index(
                fields=["supplier", "is_active"], name="catalog_supplier_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suppliercatalog",
            index=models.Index(fields=["source_type"], name="catalog_source_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="suppliercatalog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("supplier", "external_id"),
                name="uniq_supplier_catalog_external_id",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productspecification",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications",
                to="products.product",
            ),
        ),
        migrations.AddIndex(
            model_name="productcollection",
            index=models.Index(
                fields=["is_active", "is_featured", "order"],
                name="collection_active_feat_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productcollection",
            index=models.Index(
                fields=["starts_at", "ends_at"], name="collection_window_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="industry",
            index=models.Index(
                fields=["is_active", "is_featured", "order"],
                name="industry_active_feature_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="imprintmethod",
            index=models.Index(
                fields=["is_active", "order"], name="imprint_active_order_idx"
            ),
        ),
        migrations.AddField(
            model_name="homepageproductrail",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homepage_product_rails",
                to="products.category",
            ),
        ),
        migrations.AddField(
            model_name="homepageproductrail",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homepage_product_rails",
                to="products.productcollection",
            ),
        ),
        migrations.AddField(
            model_name="homepageproductrail",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homepage_product_rails",
                to="products.industry",
            ),
        ),
        migrations.AddField(
            model_name="homepageproductrail",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="homepage_rails", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="collections",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.productcollection"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="imprint_methods",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.imprintmethod"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="industry_groups",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.industry"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "is_active", "order"],
                name="variant_product_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["sku"], name="variant_sku_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["supplier_sku"], name="variant_supplier_sku_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["inventory_status"], name="variant_inventory_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sku", ""), _negated=True),
                fields=("product", "sku"),
                name="uniq_product_variant_sku",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("product",),
                name="uniq_default_variant_per_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("inventory_quantity__isnull", True),
                    ("inventory_quantity__gte", 0),
                    _connector="OR",
                ),
                name="product_variant_inventory_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="productspecification",
            index=models.Index(
                fields=["product", "order"], name="spec_product_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productspecification",
            constraint=models.UniqueConstraint(
                fields=("product", "name"), name="uniq_product_specification_name"
            ),
        ),
        migrations.AddIndex(
            model_name="homepageproductrail",
            index=models.Index(
                fields=["is_active", "order"], name="homepage_rail_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="homepageproductrail",
            index=models.Index(
                fields=["starts_at", "ends_at"], name="homepage_rail_window_idx"
            ),
        ),
    ]
