# Generated by Django 4.2.26 on 2026-09-10 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0018_homepageproductrail_imprintmethod_industry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierPriceBreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("price_uom", models.CharField(blank=True, max_length=20)),
                ("discount_code", models.CharField(blank=True, max_length=20)),
                ("part_id", models.CharField(blank=True, max_length=100)),
                ("part_description", models.CharField(blank=True, max_length=255)),
                ("effective_date", models.DateTimeField(blank=True, null=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_price_breaks",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["min_quantity"],
            },
        ),
        migrations.AddConstraint(
            model_name="supplierpricebreak",
            constraint=models.UniqueConstraint(
                fields=("product", "part_id", "min_quantity"),
                name="unique_supplier_product_part_price_break",
            ),
        ),
    ]
