# Generated by Django 4.2.26 on 2026-09-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0019_supplierpricebreak_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="supplier_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
