# Generated by Django 4.2.26 on 2026-10-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0021_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
