# Generated by Django 4.2.26 on 2026-10-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_colors_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HPGWeeklySyncCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=40, unique=True)),
                ('completed_product_ids', models.JSONField(blank=True, default=list)),
                ('window_days', models.PositiveIntegerField(default=8)),
                ('cycle_started_at', models.DateTimeField(blank=True, null=True)),
                ('cycle_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_product_id', models.CharField(blank=True, default='', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('brand',),
            },
        ),
    ]
