# Generated by Django 4.2.26 on 2026-10-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0023_hpgweeklysynccheckpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyWeeklySyncCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_key",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                ("checkpoint", models.JSONField(blank=True, default=dict)),
                ("window_days", models.PositiveIntegerField(default=8)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("supplier_key",),
            },
        ),
    ]
