# Generated by Django 4.2.26 on 2026-07-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("supplier_code", models.CharField(max_length=50, unique=True)),
                ("api_enabled", models.BooleanField(default=False)),
                ("api_url", models.URLField(blank=True)),
                ("api_key", models.CharField(blank=True, max_length=300)),
                ("ftp_host", models.CharField(blank=True, max_length=200)),
                ("ftp_username", models.CharField(blank=True, max_length=200)),
                ("ftp_password", models.CharField(blank=True, max_length=200)),
                ("active", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
