# Generated by Django 4.2.26 on 2026-07-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_artworkproof"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
