# Generated by Django 4.2.26 on 2026-07-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_order_shipping_email_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_pdf",
            field=models.FileField(blank=True, null=True, upload_to="orders/invoices/"),
        ),
    ]
