# Generated by Django 4.2.26 on 2026-07-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0009_customeraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="unpaid",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_checkout_session_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
