# Generated by Django 4.2.26 on 2026-07-14 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_supplierpurchaseorderactivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0010_order_paid_at_order_payment_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipment_number", models.CharField(max_length=40, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("label_created", "Label Created"),
                            ("ready", "Ready for Pickup"),
                            ("in_transit", "In Transit"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("exception", "Delivery Exception"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("carrier", models.CharField(blank=True, max_length=80)),
                ("service_level", models.CharField(blank=True, max_length=100)),
                ("tracking_number", models.CharField(blank=True, max_length=160)),
                ("tracking_url", models.URLField(blank=True)),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("estimated_ship_date", models.DateField(blank=True, null=True)),
                ("estimated_delivery_date", models.DateField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="customers.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.SlugField(unique=True)),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("ground", "Ground"),
                            ("two_day", "2-Day"),
                            ("overnight", "Overnight"),
                            ("pickup", "Local Pickup"),
                            ("supplier", "Supplier Shipping"),
                        ],
                        default="ground",
                        max_length=30,
                    ),
                ),
                ("carrier", models.CharField(blank=True, max_length=80)),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "estimated_days_min",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "estimated_days_max",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["base_price", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_status", models.CharField(blank=True, max_length=30)),
                ("new_status", models.CharField(max_length=30)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipment_status_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="customers.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("sku", models.CharField(blank=True, max_length=120)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipment_items",
                        to="customers.orderitem",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="customers.shipment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="customers.shippingmethod",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="supplier_purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="products.supplierpurchaseorder",
            ),
        ),
    ]
