# Generated by Django 4.2.26 on 2026-07-14 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0011_shipment_shippingmethod_shipmentstatushistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="customers.shippingmethod",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
