# Generated by Django 4.2.26 on 2026-07-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0012_order_shipping_method_order_shipping_method_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="packing_slip",
            field=models.FileField(
                blank=True, null=True, upload_to="shipments/packing_slips/"
            ),
        ),
    ]
