# Generated by Django 4.2.26 on 2026-07-17 01:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0015_supportticket_supportticketmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(blank=True, max_length=32, unique=True),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("return", "Return"),
                            ("replacement", "Replacement"),
                            ("damaged", "Damaged Item"),
                            ("wrong_item", "Wrong Item"),
                            ("missing_item", "Missing Item"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("damaged", "Product arrived damaged"),
                            ("defective", "Product is defective"),
                            ("wrong_item", "Wrong product received"),
                            ("missing_item", "Product or quantity missing"),
                            ("not_as_expected", "Product not as expected"),
                            ("quality", "Quality concern"),
                            ("shipping_damage", "Shipping damage"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("information_requested", "Information Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("awaiting_return", "Awaiting Return"),
                            ("item_received", "Item Received"),
                            ("replacement_processing", "Replacement Processing"),
                            ("refund_processing", "Refund Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="submitted",
                        max_length=40,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not Determined"),
                            ("refund", "Refund"),
                            ("replacement", "Replacement"),
                            ("store_credit", "Store Credit"),
                            ("repair", "Repair"),
                            ("no_action", "No Action"),
                        ],
                        max_length=30,
                    ),
                ),
                ("customer_notes", models.TextField()),
                ("staff_notes", models.TextField(blank=True)),
                (
                    "rma_number",
                    models.CharField(blank=True, max_length=40, null=True, unique=True),
                ),
                (
                    "return_tracking_number",
                    models.CharField(blank=True, max_length=160),
                ),
                ("return_tracking_url", models.URLField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to="customers.order",
                    ),
                ),
                (
                    "replacement_shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_return_requests",
                        to="customers.shipment",
                    ),
                ),
                (
                    "support_ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_requests",
                        to="customers.supportticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnRequestMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_internal", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_request_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="customers.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("sku", models.CharField(blank=True, max_length=120)),
                (
                    "quantity_requested",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("quantity_approved", models.PositiveIntegerField(default=0)),
                ("quantity_received", models.PositiveIntegerField(default=0)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("unopened", "Unopened"),
                            ("opened", "Opened"),
                            ("damaged", "Damaged"),
                            ("defective", "Defective"),
                            ("missing", "Missing"),
                            ("wrong_item", "Wrong Item"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not Determined"),
                            ("refund", "Refund"),
                            ("replacement", "Replacement"),
                            ("store_credit", "Store Credit"),
                            ("no_action", "No Action"),
                        ],
                        max_length=30,
                    ),
                ),
                ("customer_item_notes", models.TextField(blank=True)),
                ("staff_item_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_request_items",
                        to="customers.orderitem",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="customers.returnrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnRequestAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="returns/evidence/")),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="customers.returnrequestmessage",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="customers.returnrequest",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnRequestActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("status_changed", "Status Changed"),
                            ("assigned", "Assigned"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("rma_created", "RMA Created"),
                            ("message_added", "Message Added"),
                            ("attachment_added", "Attachment Added"),
                            ("item_received", "Item Received"),
                            ("replacement_created", "Replacement Created"),
                            ("completed", "Completed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("previous_value", models.CharField(blank=True, max_length=255)),
                ("new_value", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="customers.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["request_number"], name="customers_r_request_64e880_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(fields=["status"], name="customers_r_status_64fc3d_idx"),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["request_type"], name="customers_r_request_21507e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["requested_at"], name="customers_r_request_5b53d5_idx"
            ),
        ),
    ]
