# Generated by Django 4.2.26 on 2026-07-17 02:40

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "customers",
            "0016_returnrequest_returnrequestmessage_returnrequestitem_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("partially_refunded", "Partially Refunded"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                ],
                default="unpaid",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_number",
                    models.CharField(blank=True, max_length=32, unique=True),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("returned_items", "Returned Items"),
                            ("damaged_items", "Damaged Items"),
                            ("missing_items", "Missing Items"),
                            ("wrong_items", "Wrong Items"),
                            ("duplicate_charge", "Duplicate Charge"),
                            ("pricing_error", "Pricing Error"),
                            ("service_issue", "Service Issue"),
                            ("order_cancelled", "Order Cancelled"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("under_review", "Under Review"),
                            ("information_requested", "Information Requested"),
                            ("approved", "Approved"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=40,
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "amount_approved",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "amount_refunded",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("customer_notes", models.TextField()),
                ("staff_notes", models.TextField(blank=True)),
                ("failure_message", models.TextField(blank=True)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("stripe_refund_id", models.CharField(blank=True, max_length=255)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_refund_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to="customers.order",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_requests",
                        to="customers.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="RefundActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("assigned", "Assigned"),
                            ("status_changed", "Status Changed"),
                            ("amount_changed", "Amount Changed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("processing_started", "Processing Started"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("retry_started", "Retry Started"),
                            ("cancelled", "Cancelled"),
                            ("note_added", "Note Added"),
                        ],
                        max_length=40,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("previous_value", models.CharField(blank=True, max_length=255)),
                ("new_value", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "refund_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="customers.refundrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefundTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        max_length=30,
                    ),
                ),
                ("stripe_refund_id", models.CharField(blank=True, max_length=255)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("stripe_status", models.CharField(blank=True, max_length=80)),
                ("stripe_response", models.JSONField(blank=True, default=dict)),
                ("failure_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_refund_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "refund_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="customers.refundrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="customers_r_status_278dc1_idx"
                    ),
                    models.Index(
                        fields=["stripe_refund_id"],
                        name="customers_r_stripe__f21747_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="customers_r_created_798ec6_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="refundrequest",
            index=models.Index(
                fields=["refund_number"], name="customers_r_refund__212e39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refundrequest",
            index=models.Index(fields=["status"], name="customers_r_status_5e79ea_idx"),
        ),
        migrations.AddIndex(
            model_name="refundrequest",
            index=models.Index(
                fields=["requested_at"], name="customers_r_request_f77123_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refundrequest",
            index=models.Index(
                fields=["stripe_refund_id"], name="customers_r_stripe__11504e_idx"
            ),
        ),
    ]
