# Generated by Django 4.2.26 on 2026-07-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0017_alter_order_payment_status_refundrequest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=120)),
                ("api_version", models.CharField(blank=True, max_length=80)),
                ("livemode", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("ignored", "Ignored"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["stripe_event_id"],
                        name="customers_s_stripe__f024b5_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="customers_s_event_t_3b2c4e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="customers_s_status_f21f5b_idx"
                    ),
                    models.Index(
                        fields=["received_at"], name="customers_s_receive_8d4aa8_idx"
                    ),
                ],
            },
        ),
    ]
