# Generated by Django 4.2.26 on 2026-07-19 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_supplierlisting_and_more"),
        ("customers", "0018_stripewebhookevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="supplier_catalog_snapshot",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="supplier_listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="products.supplierlisting",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="supplier_minimum_quantity_snapshot",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="supplier_name_snapshot",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="supplier_product_id_snapshot",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="supplier_product_name_snapshot",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="supplier_setup_cost_snapshot",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="supplier_sku_snapshot",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="supplier_source_snapshot",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="supplier_unit_cost_snapshot",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["supplier_listing"], name="orderitem_listing_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["supplier_name_snapshot"], name="orderitem_supplier_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["supplier_sku_snapshot"], name="orderitem_supplier_sku_idx"
            ),
        ),
    ]
